from dataclasses import dataclass, field
"""
A dataclass representing the configuration for a LAMMPS simulation.
This class encapsulates various parameters needed to set up and run a simulation,
including input/output files, templates, and additional LAMMPS variables. It provides
methods to convert the configuration to LAMMPS variables and to load from a JSON file.
Attributes:
    input_script (Optional[str]): Path to the input script file. Defaults to None.
    template (str): Name of the template file. Defaults to "in.default_chain_template".
    resume_file (Optional[str]): Path to the resume file for restarting simulations. Defaults to None.
    data_file (str): Name of the data file. Defaults to "default_chain.data".
    lepton_file (str): Name of the lepton include file. Defaults to "lepton.inc".
    run (str): Name of the run. Defaults to "default_run".
    simulation (str): Name of the simulation. Defaults to "default_simulation".
    extra_vars (Dict[str, Any]): Additional LAMMPS variables as a dictionary. Defaults to an empty dict.
    regions (Optional[List[str]]): List of raw LAMMPS 'region' lines or multiline chunks. Defaults to None.
    wall_blocks (Optional[List[str]]): List of raw LAMMPS 'fix' wall blocks as strings. Defaults to None.
    walls (Optional[Dict[str, Any]]): Structured walls dictionary for compatibility. Defaults to None.
The constructor (__init__) is automatically generated by the @dataclass decorator and accepts
keyword arguments for all the above attributes. Example usage:
    config = SimulationConfig(
        simulation="my_sim",
        run="run_1",
        extra_vars={"temp": 300}
    )
"""
from typing import Dict, Any, Optional, List
import json

@dataclass
class SimulationConfig:    
    # Input/Output
    input_script: Optional[str] = None
    template: str = "in.default_chain_template"
    resume_file: Optional[str] = None  # New field for resume file path
    data_file: str = "default_chain.data"
    lepton_file: str = "simulation_templates/lepton.inc"
    dump_file: str = "simulation_templates/default_dump.inc"
    run: str = "default_run"
    simulation: str = "default_simulation"
    
    # Additional LAMMPS variables
    extra_vars: Dict[str, Any] = field(default_factory=dict)

    # New optional fields for raw LAMMPS lines from JSON
    regions: Optional[List[str]] = None        # each entry: a 'region ...' line or multiline chunk
    wall_blocks: Optional[List[str]] = None    # each entry: a 'fix ...' wall block (string / multiline)
    walls: Optional[Dict[str, Any]] = None     # keep-compatible: structured walls (converted by runner if present)
    
    # Parallelism
    num_procs: Optional[int] = None
    num_threads: int = 1
    
    # Custom output directory override
    outdir_override: Optional[str] = None

    @staticmethod
    def compute_output_dir(simulation: str, run: str) -> str:
        """Statically computes the output directory path."""
        return f"dumping_yard/{simulation}/{run}"

    @property
    def output_dir(self) -> str:
        """Constructs the output directory path from simulation and run, or uses override if provided."""
        if self.outdir_override:
            return self.outdir_override.replace("\\", "/")
        # Use forward slashes for LAMMPS compatibility even on Windows
        return self.compute_output_dir(self.simulation, self.run)

    def to_lammps_vars(self) -> Dict[str, str]:
        """Converts config to a dictionary of LAMMPS variable arguments."""
        vars_dict = {
            "outdir": str(self.output_dir),
            "template": str(self.template),
            "data_file":str(self.data_file),
            "run":str(self.run),
            "simulation":str(self.simulation)
        }
        # Add any extra variables
        for k, v in self.extra_vars.items():
            vars_dict[k] = str(v)
            
        return vars_dict

    @classmethod
    def from_json(cls, path: str) -> "SimulationConfig":
        with open(path, "r") as f:
            data = json.load(f)
        return cls(**data)